
name: Build and test

on:
  pull_request:
    branches: [master, dev]
  push:
    branches: [master, dev]

jobs:
  build-and-test:
    uses: GTNewHorizons/GTNH-Actions-Workflows/.github/workflows/build-and-test.yml@master
    secrets: inherit
